//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_json_and_Session__Project.Models.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        public Product()
        {
            this.Orderdetails = new HashSet<Orderdetail>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage ="plese do it")]

        public string name { get; set; }
        public int price { get; set; }
    
        public virtual ICollection<Orderdetail> Orderdetails { get; set; }
    }
}
