// <auto-generated />
namespace Code_First_Update.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Details : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Details));
        
        string IMigrationMetadata.Id
        {
            get { return "202205160542484_Details"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
